import React from 'react';
import { Link } from 'react-router-dom';
import './home.css'; 

const Home = () => {
    return (
        <div className="container">
            <ul>
                <li>
                    <Link 
                    to="use-memo"
                    >Use-Memo
                    </Link>
                </li>
                <li>
                    <Link 
                    to="use-effect"
                    >
                        Use-Effect
                    </Link>
                </li>
                <li>
                    <Link 
                    to="use-"
                    >
                        Use-Memo
                    </Link>
                </li>
                <li>
                    <Link 
                    to="use-param"
                    >
                        Use-Param
                    </Link>
                </li>
                <li>
                    <Link 
                    to="use-mach"
                    >
                        Use-Mach
                    </Link>
                </li>
                <li>
                    <Link 
                    to="use-state"
                    >
                        Use-State
                    </Link>
                </li>
                <li>
                    <Link 
                    to="use-navigate"
                    >
                        Use-Navigate
                    </Link>
                </li>
                <li>
                    <Link 
                    to="use-memo"
                    >
                        Use-Memo
                    </Link>
                </li>
                <li>
                    <Link 
                    to="use-memo"
                    >
                        Use-Memo
                    </Link>
                </li>
                <li>
                    <Link 
                    to="call-back-function"
                    >
                        Call-Back-Function
                    </Link>
                </li>
                <li>
                    <Link 
                    to="use-context">
                        Use-Context
                    </Link>
                </li>
                <li>
                    <Link 
                    to="memo"
                    >
                        Memo
                    </Link>
                </li>
                <li>
                    <Link 
                    to="use-reducer"
                    >
                        Use-Reducer
                    </Link>
                </li>
                <li>
                    <Link 
                    to="use-callback"
                    >
                        Use-Callback
                    </Link>
                </li>
            </ul>
        </div>
    );
}

export default Home;
